import { Schema, model } from 'mongoose';


const clientSchema = new Schema({
  id: {type: Number, required: true},
  company_name: {type: String},
  registered_business_country: {type: String},
  company_number: {type: String},
  business_type: {type: String, enum:['Limited', 'Sole Trader', 'Partnership Limited', 'Club', 'Charity']},
  date_of_incorporation_or_formation: {type: Date},
  trading_name: {type: String},
  vat_number: {type: String},
  company_document: {type: String},
  certificate_of_incorporation: {type: String},
  bank_document: {type: String},
  processing_history: {type: String},
  business_invoice: {type: String},
  marchant_category_code: {type: String},
  finance_status: {type: String},
  status:{type: String},
  substatus: {type: String},
  status_date: {type: Date},
  substatus_date: {type: Date},
  TargetEU: {type: Number, default: 25},
  TargetUK: {type: Number, default: 50},
  TargetUS: {type: Number, default: 25},
  TargetROW: {type: Number, default: 0},
  MerchantFulfilment: {type: Number, default: 5},
  RequireEwallet: {type: Boolean, default: false},
  WalletID: {type: String, default:''},
  NumberOfEmployees: {type: String},
  IsSeasonalBusiness: {type: Boolean, default: false},
  ChangeOfProcessor: {type: String},
  RecurringTransactions: {type: Boolean, default: false},
  ShoppingCarts: {type: String},
  SourceofWealth: {type: String},
  SourceofFunds: {type: String},
  BusinessTransactionsEcom: {type: Number, default: 50},
  BusinessTransactionsMOTO: {type: Number, default: 0},
  BusinessTransactionsPOS: {type: Number, default: 50},
  MonthExpectedCardVolume: {type: Number},
  AverageTransactionValue: {type: Number, default: 100},
  ChargeBackP: {type: Number, default: 0},
  RefundP: {type: Number, default: 0},
  ChosenFormCurrency: {type: String, default: "GBP"},
  Ecom: {type: Boolean},
  Moto: {type: Boolean},
  POS: {type: Boolean},
  DCC: {type: Boolean, default: false},
  EcomAmexMID: {type: String, default: ''},
  MotoAmexMID: {type: String, default: ''},
  PayByLink: {type: Boolean, default: false},
  VAU: {type: Boolean, default: false},
  ABU: {type: Boolean, default: false},
  APMs: {type: String, default: ''}
  
});
const ClientModel = model('Client', clientSchema);

export = ClientModel;

